name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install GENIUS
      run: mvn install:install-file -Dfile=resources/genius-9.1.12.jar
    - name: Build with Maven
      run: mvn -B package --file pom.xml
